/*
 * wifi_mqtt_tsk.h
 *
 *  Created on: Nov 12, 2020
 *      Author: zchaojian
 */

#ifndef COMPONENTS_WIFI_INCLUDE_WIFI_MQTT_TSK_H_
#define COMPONENTS_WIFI_INCLUDE_WIFI_MQTT_TSK_H_

#include "device_app.h"
#define DEFINE_DEVICE								2

#define CONFIG_WIFI_MQTT_DEFAULT_PUBLISH_FORMAT		"A0000R0000T00"
#define CONFIG_WIFI_MQTT_DEFAULT_SUBSCRIBE_FORMAT	"A%xR%xT%x:%d:"
#define CONFIG_WIFI_MQTT_DEFAULT_PUBLISH_MAX		100
#define CONFIG_WIFI_MQTT_DEFAULT_PUBLISH_TICKS		200

#define CONFIG_WIFI_MQTT_DEFAULT_HOST				"183.230.40.39"
#define CONFIG_WIFI_MQTT_DEFAULT_PORT				6002
#define CONFIG_WIFI_MQTT_DEFAULT_PRODUCT_ID			"364418"

#if DEFINE_DEVICE == 1
#define CONFIG_ETH_MQTT_DEFAULT_AUTH_INFOR			"20200803"
#define CONFIG_ETH_MQTT_DEFAULT_DEVICE_ID			"615226885"
#elif DEFINE_DEVICE == 2
#define CONFIG_ETH_MQTT_DEFAULT_AUTH_INFOR			"20200811"
#define CONFIG_ETH_MQTT_DEFAULT_DEVICE_ID			"617637799"
#endif

typedef struct
{
	DevicePartitionTableDataTypeTPDF tDevicePartitionTableDataType;
	char *cFromat;
	uint8_t *ucMem;
}MqttPublishDataTPDF;

#endif /* COMPONENTS_WIFI_INCLUDE_WIFI_MQTT_TSK_H_ */
